workshop:
  publishedID: 3626035263
  visibility: Public
  textFromMetadataVersion: true
  textFromMetadataMain: true
  title: 
  description: 
  internalData: 
  changes: '- Additional fixes to the mech visualization methods in inventory and in combat. Both AssetBundle-prefixed asset keys and prefab name asset keys should work correctly in all contexts.'
  tags:
  - Utilities
  - Other
  texPreviewUpload: true
configEdits: 
textEdits: 
assetBundles: 
libraryDLLs:
  files:
  - enabled: true
    relative: true
    path: Solution/ModExtensions/obj/Release/ModExtensions.dll
extraFiles: 
