workshop:
  publishedID: 3626035263
  visibility: Public
  textFromMetadataVersion: true
  textFromMetadataMain: true
  title: 
  description: 
  internalData: 
  changes: '- Disabled fixes to issues that are now officially patched in PB 2.1.1. I recommend keeping the mod installed as more issues might be discovered over time and ModExtensions might remain a dependency to mods currently using it.'
  tags:
  - Utilities
  - Other
  texPreviewUpload: true
configEdits: 
textEdits: 
assetBundles: 
libraryDLLs:
  files:
  - enabled: true
    relative: true
    path: Solution/ModExtensions/obj/Release/ModExtensions.dll
extraFiles: 
