workshop:
  publishedID: 3626035263
  visibility: Unlisted
  textFromMetadataVersion: true
  textFromMetadataMain: true
  title: 
  description: 
  internalData: 
  changes: Misc changes.
  tags:
  - Utilities
  - Other
  texPreviewUpload: true
configEdits: 
textEdits: 
assetBundles: 
libraryDLLs:
  files:
  - enabled: true
    relative: true
    path: Solution/ModExtensions/obj/Release/ModExtensions.dll
extraFiles: 
